create project  structure.
tamdev3241/Tam_Binh_Hai pull request #1
Opened 2021-11-08 08:14 UTC by tamdev3241

2021-11-08 10:13 UTC, HaiNguyenPV12 requested changes

2021-11-08 10:13 UTC, HaiNguyenPV12 commented on lib/main.dart
> +import 'package:crypto_app/src/app.dart';
We should use relative imports

2021-11-08 10:13 UTC, HaiNguyenPV12 commented on lib/src/app.dart
> +import 'package:crypto_app/src/constants/app_theme.dart';
same as above, relative imports

2021-11-08 10:13 UTC, HaiNguyenPV12 commented on lib/src/commons/app_icons.dart
> +class AppIcon {
Unnecessary? Rather than instantiating an Icon at launch. We could either make a custom widget for the entire app or just pass this value in whenever we need to,

2021-11-08 10:13 UTC, HaiNguyenPV12 commented on lib/src/constants/constant.dart
> +  static const String init = '/';
Should use a noun here

2021-11-08 10:13 UTC, HaiNguyenPV12 commented on lib/src/routes/route_controller.dart
> +import 'package:crypto_app/src/constants/constant.dart';
Use relative imports

2021-11-08 10:32 UTC, thanhphamtrung commented on lib/src/config/app_config.dart
> +import 'package:flutter/cupertino.dart';
should use material instead of cupertino

2021-11-08 10:34 UTC, thanhphamtrung commented on lib/src/constants/app_theme.dart
> +    // highlightColor: AppColors.primary.withOpacity(0.2),
why you cmt these lines?

2021-11-08 10:34 UTC, thanhphamtrung commented on lib/src/constants/app_theme.dart
> +        // statusBarColor: AppColors.primary,
same as above

2021-11-08 10:37 UTC, thanhphamtrung commented on lib/src/screens/home_screen/home_screen.dart
> +          ],
I think we should move BottomNavigationBar to a separate file as a screen

2021-11-08 10:41 UTC, thanhphamtrung requested changes

2021-11-08 10:41 UTC, thanhphamtrung commented on lib/src/config/app_config.dart
> +import 'package:flutter/cupertino.dart';
should use material instead of cupertino

2021-11-08 10:41 UTC, thanhphamtrung commented on lib/src/constants/app_theme.dart
> +    // highlightColor: AppColors.primary.withOpacity(0.2),
why you cmt these lines?

2021-11-08 10:41 UTC, thanhphamtrung commented on lib/src/constants/app_theme.dart
> +        // statusBarColor: AppColors.primary,
same as above

2021-11-08 10:41 UTC, thanhphamtrung commented on lib/src/screens/home_screen/home_screen.dart
> +import 'package:crypto_app/src/screens/home_screen/pages/categories_page.dart';
import

2021-11-08 10:41 UTC, thanhphamtrung commented on lib/src/screens/home_screen/home_screen.dart
> +          ],
I think we should move BottomNavigationBar to a separate file as a screen

2021-11-08 13:15 UTC, tamdev3241 commented on lib/main.dart
> +import 'package:crypto_app/src/app.dart';
I fixed it

2021-11-08 13:15 UTC, tamdev3241 commented on lib/src/app.dart
> +import 'package:crypto_app/src/constants/app_theme.dart';
i fixed it

2021-11-08 13:16 UTC, tamdev3241 commented on lib/src/commons/app_icons.dart
> +class AppIcon {
I deleted AppIcon

2021-11-08 13:17 UTC, tamdev3241 commented on lib/src/constants/constant.dart
> +  static const String init = '/';
I fixed it

2021-11-08 13:17 UTC, tamdev3241 commented on lib/src/routes/route_controller.dart
> +import 'package:crypto_app/src/constants/constant.dart';
i fixed it

2021-11-08 13:17 UTC, tamdev3241 commented on lib/src/config/app_config.dart
> +import 'package:flutter/cupertino.dart';
I fixed it

2021-11-08 13:18 UTC, tamdev3241 commented on lib/src/constants/app_theme.dart
> +        // statusBarColor: AppColors.primary,
i fixed it

2021-11-08 13:21 UTC, tamdev3241 commented on lib/src/screens/home_screen/home_screen.dart
> +          ],
I moved BottomNavigationBar of HomeScreen to a separate widget

2021-11-08 14:25 UTC, HaiNguyenPV12 requested changes
Just a few minor changes

2021-11-08 14:25 UTC, HaiNguyenPV12 commented on lib/main.dart
> +import 'src/config/app_config.dart';
we should have a line break between local imports and public packages

2021-11-08 14:25 UTC, HaiNguyenPV12 commented on lib/src/app.dart
> +import 'constants/constant.dart';
same as above

2021-11-08 14:25 UTC, HaiNguyenPV12 commented on lib/src/config/app_config.dart
> +import 'constants.dart';
same as above

2021-11-08 14:25 UTC, HaiNguyenPV12 commented on lib/src/constants/app_theme.dart
> +
same as above

2021-11-08 14:25 UTC, HaiNguyenPV12 commented on lib/src/screens/home_screen/home_screen.dart
> +import 'pages/categories_page.dart';
same as above

2021-11-08 14:25 UTC, HaiNguyenPV12 commented on lib/src/widgets/bottom_navigation_home_screen.dart
> +import '../constants/constant.dart' as constant;
same as above

2021-11-08 14:27 UTC, HaiNguyenPV12 commented on lib/src/constants/constant.dart
> +  static const String init = '/';
I'm still seeing it as `init` as of the latest commit? We shouldn't be using a verb here.

2021-11-08 14:54 UTC, LaggeR2204 commented on lib/src/constants/constant.dart
> +  static const String init = '/';
i changed it to `initial`

2021-11-08 15:00 UTC, LaggeR2204 commented on lib/main.dart
> +import 'src/config/app_config.dart';
I added a line break between local imports and public packages

2021-11-08 15:00 UTC, LaggeR2204 commented on lib/src/app.dart
> +import 'constants/constant.dart';
I fixed it

2021-11-08 15:00 UTC, LaggeR2204 commented on lib/src/config/app_config.dart
> +import 'constants.dart';
I fixed it

2021-11-08 15:00 UTC, LaggeR2204 commented on lib/src/constants/app_theme.dart
> +
I fixed it

2021-11-08 15:01 UTC, LaggeR2204 commented on lib/src/screens/home_screen/home_screen.dart
> +import 'pages/categories_page.dart';
I fixed it

2021-11-08 15:01 UTC, LaggeR2204 commented on lib/src/widgets/bottom_navigation_home_screen.dart
> +import '../constants/constant.dart' as constant;
I fixed it

2021-11-09 02:44 UTC, thanhphamtrung approved these changes

2021-11-09 02:47 UTC, HaiNguyenPV12 approved these changes

2021-11-09 02:53 UTC, merged