buid UI of coins list and coins filterd by category
tamdev3241/Tam_Binh_Hai pull request #4
Opened 2021-11-10 09:53 UTC by haitran0508

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/constants/constant.dart
> +  static const String filterSelect = '/filterSelect';
name route as a noun

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/routes/route_controller.dart
> +import 'package:crypto_app/src/screens/home_screen/pages/filter_select_screen.dart';
import

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +import 'package:crypto_app/src/dummy/dummy_list.dart';
import

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +        title: const Text('[Category]'),
hard code

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +              height: 40,
variable for layout

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +                padding: EdgeInsets.fromLTRB(sidePadding, 0, sidePadding, 0),
why don't you use EdgeInsets.symestirc

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +                    borderRadius: const BorderRadius.only(
BorderRadius.horizonta

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +              // flex: 6,
remove if it's not necessary

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +                padding: const EdgeInsets.fromLTRB(
EdgeInsets.symmetric

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +                        'https://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/1024/Bitcoin-BTC-icon.png'),
hard code

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/home_screen/home_screen.dart
> +import '../../dummy/dummy_list.dart';
sort import

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/home_screen/pages/all_coin_page.dart
> +import '../../../widgets/coin_overview_widget.dart';
have a line between

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/home_screen/pages/all_coin_page.dart
> +          Navigator.pushNamed(context, '/filterSelect');
use route constants

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/home_screen/pages/all_coin_page.dart
> +            fontWeight: FontWeight.bold,
use app Theme

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/home_screen/pages/all_coin_page.dart
> +                8,
make it on a line for a better look

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/home_screen/pages/all_coin_page.dart
> +  Widget _buildTextButton(BuildContext context, String text) {
consider making it be a widget

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/home_screen/pages/filter_select_screen.dart
> +      appBar: AppBar(title: Text('Select [Criteria]')),
hard code

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/home_screen/pages/filter_select_screen.dart
> +          0,
EdgeInsets.symmetric

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/screens/home_screen/pages/filter_select_screen.dart
> +              fontSize: 18,
use app theme

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/widgets/coin_overview_widget.dart
> +  final String name1;
name1 name2 are so confused

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/widgets/coin_overview_widget.dart
> +  final double? rightPadding;
as I have said, padding should be controlled by the parent widget

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/widgets/coin_search_delegate.dart
> +  // final List<String> coinsSuggestions;
remove

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/widgets/coin_search_delegate.dart
> +          // query = '';
??

2021-11-11 15:23 UTC, thanhphamtrung commented on lib/src/widgets/coin_search_delegate.dart
> +  }
it seems to be the same

2021-11-12 06:18 UTC, haitran0508 commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +        title: const Text('[Category]'),
The text of title should be taken from CategoryScreen when user click to choose the category. Binh and I will work on to integrate the state management.
Looking forward to your advice

2021-11-12 06:19 UTC, haitran0508 commented on lib/src/widgets/coin_overview_widget.dart
> +  final double? rightPadding;
About this widget, these 4 paddings are used for internal layout of its own. For example below, I set padding from parent widget to the CoinOverview is 16, which is white space between edge of the screen to the icon. And I set topPadding and bottomPadding of the widget is 13, which is the blue space surround the icon and texts. I just thought that it will be better for us to customize the widget in future if there are any changes.
Looking forward to your advice

<img width="342" alt="image" src="https://user-images.githubusercontent.com/93150875/141419349-7b1b4f23-64d9-44a1-8301-2ce1c49eec44.png">

2021-11-12 06:19 UTC, haitran0508 commented on lib/src/widgets/coin_search_delegate.dart
> +  }
As temporary, I just created a sample list for both searching and suggestions. In future when we have successfully had a more clear view about list of coins, I will create a better suggestions list that suitable for users.

2021-11-12 06:27 UTC, haitran0508 commented on lib/src/routes/route_controller.dart
> +import 'package:crypto_app/src/screens/home_screen/pages/filter_select_screen.dart';
fixed

2021-11-12 06:27 UTC, haitran0508 commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +import 'package:crypto_app/src/dummy/dummy_list.dart';
fixed

2021-11-12 06:27 UTC, haitran0508 commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +              height: 40,
fixed

2021-11-12 06:27 UTC, haitran0508 commented on lib/src/widgets/coin_overview_widget.dart
> +  final String name1;
fixed

2021-11-12 06:27 UTC, haitran0508 commented on lib/src/widgets/coin_search_delegate.dart
> +  // final List<String> coinsSuggestions;
fixed

2021-11-12 06:27 UTC, haitran0508 commented on lib/src/widgets/coin_search_delegate.dart
> +          // query = '';
fixed

2021-11-12 06:28 UTC, haitran0508 commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +                padding: EdgeInsets.fromLTRB(sidePadding, 0, sidePadding, 0),
fixed

2021-11-12 06:28 UTC, haitran0508 commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +                    borderRadius: const BorderRadius.only(
fixed

2021-11-12 06:28 UTC, haitran0508 commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +              // flex: 6,
fixed

2021-11-12 06:28 UTC, haitran0508 commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +                padding: const EdgeInsets.fromLTRB(
fixed

2021-11-12 06:29 UTC, haitran0508 commented on lib/src/screens/coin_by_category_screen/coin_by_category_screen.dart
> +                        'https://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/1024/Bitcoin-BTC-icon.png'),
I have tried creating a sample json for this purpose. Thank you!

2021-11-12 06:29 UTC, haitran0508 commented on lib/src/screens/home_screen/home_screen.dart
> +import '../../dummy/dummy_list.dart';
fixed

2021-11-12 06:29 UTC, haitran0508 commented on lib/src/screens/home_screen/pages/all_coin_page.dart
> +import '../../../widgets/coin_overview_widget.dart';
fixed

2021-11-12 06:29 UTC, haitran0508 commented on lib/src/screens/home_screen/pages/all_coin_page.dart
> +          Navigator.pushNamed(context, '/filterSelect');
fixed

2021-11-12 06:29 UTC, haitran0508 commented on lib/src/screens/home_screen/pages/all_coin_page.dart
> +                8,
fixed

2021-11-12 06:30 UTC, haitran0508 commented on lib/src/screens/home_screen/pages/all_coin_page.dart
> +  Widget _buildTextButton(BuildContext context, String text) {
fixed

2021-11-12 06:33 UTC, haitran0508 commented on lib/src/screens/home_screen/pages/filter_select_screen.dart
> +      appBar: AppBar(title: Text('Select [Criteria]')),
I will implement the state management to update name of [Criteria] when working on fetching API.
Looking forward to you advice

2021-11-12 06:33 UTC, haitran0508 commented on lib/src/screens/home_screen/pages/filter_select_screen.dart
> +          0,
fixed

2021-11-12 06:33 UTC, haitran0508 commented on lib/src/screens/home_screen/pages/filter_select_screen.dart
> +              fontSize: 18,
fixed

2021-11-15 05:13 UTC, HaiNguyenPV12 commented on lib/src/widgets/coin_overview_widget.dart
> +
what happens when the parameterized value is null or empty?

2021-11-15 06:32 UTC, haitran0508 commented on lib/src/widgets/coin_overview_widget.dart
> +
I have added null-check for those parameters. 
Looking forward to your comments.

2021-11-15 06:35 UTC, thanhphamtrung submitted a review, later dismissed

2021-11-15 06:36 UTC, HaiNguyenPV12 requested changes

2021-11-15 06:36 UTC, HaiNguyenPV12 commented on lib/src/widgets/coin_overview_widget.dart
> +
Should bring `N/A` to a constant

2021-11-15 06:44 UTC, haitran0508 commented on lib/src/widgets/coin_overview_widget.dart
> +
Hi Hai, it is updated as requested

2021-11-15 08:30 UTC, HaiNguyenPV12 approved these changes

2021-11-15 08:58 UTC, thanhphamtrung approved these changes

2021-11-15 09:04 UTC, merged